language: python
python:
  # - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
  # - "3.7"
install:
    - pip install -r requirements.txt
    - python setup.py install
    - recli init -f
script:
    - sh tests/units/unit_tests.sh
    - python tests/e2e/execute_all_commands.py > /dev/null
